import type { Product, Store } from "~/shared/api/client";

export const staticStores: Store[] = [
  {
    id: "static-design-market",
    name: "Design Market",
    url: "design-market",
    description: "Digital templates, product assets, and custom storefront kits.",
    isVerified: false,
    ownerUsername: "designmarket",
    tagNames: ["Graphics & Design", "Digital Marketing"],
    previewImage: null,
    rating: { likes: 128, dislikes: 3, reviewsCount: 64 },
  },
  {
    id: "static-code-lab",
    name: "Code Lab",
    url: "code-lab",
    description: "Small software tools, scripts, integrations, and code reviews.",
    isVerified: false,
    ownerUsername: "codelab",
    tagNames: ["Programming & Tech", "Business"],
    previewImage: null,
    rating: { likes: 94, dislikes: 2, reviewsCount: 37 },
  },
  {
    id: "static-media-vault",
    name: "Media Vault",
    url: "media-vault",
    description: "Stock clips, music loops, motion graphics, and audio packs.",
    isVerified: false,
    ownerUsername: "mediavault",
    tagNames: ["Music & Audio", "Video & Animation"],
    previewImage: null,
    rating: { likes: 76, dislikes: 4, reviewsCount: 28 },
  },
  {
    id: "static-secure-goods",
    name: "Secure Goods",
    url: "secure-goods",
    description: "Curated digital goods sold with escrow-backed checkout.",
    isVerified: false,
    ownerUsername: "securegoods",
    tagNames: ["Electronics, Computers & Parts", "Data"],
    previewImage: null,
    rating: { likes: 151, dislikes: 5, reviewsCount: 82 },
  },
  {
    id: "static-writers-room",
    name: "Writers Room",
    url: "writers-room",
    description: "Copywriting, translation, editing, and launch content.",
    isVerified: false,
    ownerUsername: "writersroom",
    tagNames: ["Writing & Translation", "Business"],
    previewImage: null,
    rating: { likes: 67, dislikes: 1, reviewsCount: 19 },
  },
  {
    id: "static-indie-shelf",
    name: "Indie Shelf",
    url: "indie-shelf",
    description: "Games, books, learning resources, and creator-made downloads.",
    isVerified: false,
    ownerUsername: "indieshelf",
    tagNames: ["Films, Music & Games", "Books"],
    previewImage: null,
    rating: { likes: 119, dislikes: 6, reviewsCount: 45 },
  },
];

export const staticProducts: Product[] = [
  {
    id: "static-product-landing-kit",
    name: "Launch Landing Kit",
    description: "A polished starter pack for storefront announcements.",
    shortDescription: "Hero copy, launch graphics, and reusable product sections.",
    category: "Graphics & Design",
    price: 49,
    storeUrl: "design-market",
    previewImage: null,
    galleryImages: [],
    imageIds: [],
    hasPreview: false,
    rating: { likes: 43, dislikes: 1, reviewsCount: 18 },
  },
  {
    id: "static-product-automation-pack",
    name: "Automation Script Pack",
    description: "Utility scripts for small storefront operations.",
    shortDescription: "CSV cleanup, order exports, and notification helpers.",
    category: "Programming & Tech",
    price: 79,
    storeUrl: "code-lab",
    previewImage: null,
    galleryImages: [],
    imageIds: [],
    hasPreview: false,
    rating: { likes: 58, dislikes: 2, reviewsCount: 21 },
  },
  {
    id: "static-product-audio-loops",
    name: "Creator Audio Loops",
    description: "Short audio loops for videos, games, and social posts.",
    shortDescription: "Royalty-friendly loops for creator projects.",
    category: "Music & Audio",
    price: 24,
    storeUrl: "media-vault",
    previewImage: null,
    galleryImages: [],
    imageIds: [],
    hasPreview: false,
    rating: { likes: 36, dislikes: 0, reviewsCount: 12 },
  },
];
