import "./globals.css";
import '@park-ui/tailwind-plugin/preset.css'
import '@rainbow-me/rainbowkit/styles.css';
import 'react-indiana-drag-scroll/dist/style.css';

import type { Metadata } from "next";

import { cn } from "~/shared/lib/cn";
import { fontInter } from "~/shared/assets/fonts/inter";
import { fontManrope } from "~/shared/assets/fonts/manrope";
import { NavHeader } from "~/widgets/nav-header";
import { Footer } from "~/widgets/footer";
import { Providers } from "./_providers";

import { RegisterFlowDialog } from "~/widgets/register-flow";
import { UserProfileSettingsDialog } from "~/widgets/user/profile-settings";

const fontVariables = [fontInter.variable, fontManrope.variable];

export const metadata: Metadata = {
	title: "Sella.me",
	description: "Generated by create next app",
};

export default function RootLayout({
	children,
}: Readonly<{
	children: React.ReactNode;
}>) {
	return (
		<html lang="en">
			<body className={cn(...fontVariables, 'bg-black-06 text-white font-inter')}>
				<Providers>
					<NavHeader className='sticky top-[1rem] w-[calc(100%-2rem)] mx-auto z-header' />
					<div className='w-full min-h-full pt-[5rem] pb-[7.5rem]'>
						{children}
					</div>
					<Footer />

					<RegisterFlowDialog />
					<UserProfileSettingsDialog />
				</Providers>
			</body>
		</html>

	);
}
