import type { Metadata } from "next";
import "./globals.css";
import '@park-ui/tailwind-plugin/preset.css'
import { cn } from "~/shared/lib/cn";

import { fontInter } from "~/shared/assets/fonts/inter";
import { fontManrope } from "~/shared/assets/fonts/manrope";
import { NavHeader } from "~/widgets/nav-header";
import { Footer } from "~/widgets/footer";

const fontVariables = [fontInter.variable, fontManrope.variable];

export const metadata: Metadata = {
	title: "Sella.store",
	description: "Generated by create next app",
};

export default function RootLayout({
	children,
}: Readonly<{
	children: React.ReactNode;
}>) {
	return (
		<html lang="en">
			<body className={cn(...fontVariables, 'bg-black-06 text-white font-inter')}>
				<NavHeader className='sticky top-[1rem] w-[calc(100%-2rem)] mx-auto z-header' />
				<div className='w-full min-h-full pt-[5rem] pb-[7.5rem]'>
					{children}
				</div>
				<Footer />
			</body>
		</html>
	);
}
